name: salyan_file_manager
description: Salyan File Manager
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  open_filex: ^4.5.0
  permission_handler: ^11.3.0

flutter:
  uses-material-design: true
