name: Build APK (Debug)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.22.3

    - name: Bootstrap Flutter project
      run: |
        if [ -f .ci_bootstrap ]; then
          flutter create .
          rm .ci_bootstrap
        fi

    - run: flutter pub get
    - run: flutter build apk --debug --split-per-abi

    - uses: actions/upload-artifact@v4
      with:
        name: SalyanFileManager-debug.apk
        path: build/app/outputs/flutter-apk/*.apk

